ViewModels/AddressViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ContactManager.ViewModels
{
    public class AddressViewModel
    {
        public int Id { get; set; }
        [Required]
        public string FullAddress { get; set; }
        public string AddressType { get; set; }
    }
}

ViewModels/ClientViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ContactManager.ViewModels
{
    public class ClientViewModel
    {
        public int ClientId { get; set; }
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }
        public ICollection<AddressViewModel> Addresses { get; set; }
    }
}

Controllers/AddressesController.cs
using AutoMapper;
using ContactManager.Data;
using ContactManager.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ContactManager.Controllers
{
    [Route("api/[Controller]")]
    public class AddressesController : Controller
    {
        private readonly IContactRepository _repository;
        private readonly IMapper _mapper;

        public AddressesController(IContactRepository repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Get(int clientId)
        {
            var client = _repository.GetClientById(clientId);
            if (client != null) return Ok(_mapper.Map<IEnumerable<AddressViewModel>>(client.Addresses));
            return NotFound();
        }

        [HttpGet("{id}")]
        public IActionResult Get(int clientId, int id)
        {
            var client = _repository.GetClientById(clientId);
            if (client != null)
            {
                var address = client.Addresses.Where(c => c.Id == id).FirstOrDefault();

                if (address != null)
                {
                    return Ok(_mapper.Map<AddressViewModel>(address));
                }
            }
            return NotFound();
        }
    }
}

Controllers/AppController.cs
using AutoMapper;
using ContactManager.Data;
using ContactManager.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace ContactManager.Controllers
{
    public class AppController : Controller
    {
        private readonly IContactRepository _repository;
        private readonly IMapper _mapper;

        public AppController(IContactRepository repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Get(bool includeAddresses = true)
        {
            try
            {
                var results = _repository.GetAllClients(includeAddresses);
                return Ok(_mapper.Map<IEnumerable<ClientViewModel>>(results));
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpGet]
		public IActionResult Create()
		{
			return View();
		}
	}
}

Controllers/ClientsController.cs
using AutoMapper;
using ContactManager.Data;
using ContactManager.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ContactManager.Controllers
{
    [Route("api/[Controller]")]
    public class ClientsController : Controller
    {
        private readonly IContactRepository _repository;
        private readonly IMapper _mapper;

        public ClientsController(IContactRepository repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Get(bool includeAddresses = true)
        {
            try
            {
                var results = _repository.GetAllClients(includeAddresses);
                return Ok(_mapper.Map<IEnumerable<ClientViewModel>>(results));
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

Views/App/Create.cshtml
@model Client

<h1>Add a new Contact</h1>

<form asp-controller="Contacts" asp-action="Create" class="form-horizontal" role="form">

    <div class="form-group">
        <label asp-for="FirstName" class="col-md-3 control-label"></label>
    <div class="col-md-9">
        <input asp-for="FirstName" class="form-control">
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    </div>

    <div class="form-group">
        <label asp-for="LastName" class="col-md-3 control-label"></label>
        <div class="col-md-9">
            <input asp-for="LastName" class="form-control">
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Address" class="col-md-3 control-label"></label>
        <div class="col-md-9">
            <input asp-for="Address" class="form-control">
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-9 col-sm-offset-3">
            <button type="submit" class="btn btn-primary">Add Contact</button>
            <a class="btn btn-default" asp-controller="Contacts" asp-action="Index">Cancel</a>
        </div>
    </div>
</form>

Views/App/Delete.cshtml
@model Client

<h1>Confirm Delete</h1>

<h3>Are you sure that you want to delete @Model.FirstName @Model.LastName?</h3>

<form asp-action="Destroy" asp-route-id="@Model.Id" >
    <button type="submit" class="btn btn-danger">Delete Contact</button>
    <a asp-action="Index">Cancel</a>
</form>

Views/App/Edit.cshtml
@model Client

<h1>Edit Contact</h1>

<form asp-controller="Contacts" asp-action="Edit" class="form-horizontal" role="form">
    <input type="hidden" asp-for="Id">
    
    <div class="form-group">
    <label asp-for="FirstName" class="col-md-3 control-label"></label>
    <div class="col-md-9">
        <input asp-for="FirstName" class="form-control">
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    </div>

    <div class="form-group">
        <label asp-for="LastName" class="col-md-3 control-label"></label>
        <div class="col-md-9">
            <input asp-for="LastName" class="form-control">
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Address" class="col-md-3 control-label"></label>
        <div class="col-md-9">
            <input asp-for="Address" class="form-control">
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-9 col-sm-offset-3">
            <button type="submit" class="btn btn-primary">Save Contact</button>
            <a class="btn btn-default" asp-controller="Contacts" asp-action="Index">Cancel</a>
        </div>
    </div>
</form>

Views/App/Index.cshtml
@model IEnumerable<Client>

<h2>Contact Manager</h2>

<h3>Contact List</h3>
<table class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Address</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    @if(Model != null)
    {
        @foreach(var contact in Model)
        {
        <tr>
          <td>@contact.FirstName</td>
          <td>@contact.LastName</td>
          <td>@contact.Addresses</td>
          <td>
            <a asp-controller="Contacts" asp-action="Edit" asp-route-id="@contact.Id">Edit</a>
            |
            <a asp-controller="Contacts" asp-action="Delete" asp-route-id="@contact.Id">Delete</a>
          </td>
        </tr>
        }      
    }
  </tbody>
</table>

<p><a asp-controller="Contacts" asp-action="Create" class="btn btn-default">Add a new Contact</a></p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <title>Contact Manager: @ViewBag.Title</title>
  <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
  <div class="row">
    <header class="container-fluid">
      <nav class="navbar navbar-dark bg-dark navbar-expand-md">
        <h1 class="navbar-brand"><i class="fas fa-paint-brush"></i>Contact Manager</h1>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div id="theMenu" class="navbar-collapse collapse">
          <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Index">Home</a></li>
            <li class="nav-item"><a class="nav-link" asp-controller="Clients" asp-action="Index">Clients</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <section class="container">
      <h2 class="text-center">@ViewBag.Title</h2>
      @RenderBody()
    </section>
    <footer class="container">
      <div class="text-center">Copyright 2022 Contact Manager</div>
    </footer>
  </div>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/lib/fortawesome/fontawesome-free/js/fontawesome.js"></script>
  <script src="~/lib/fortawesome/fontawesome-free/js/solid.js"></script>
  <script src="~/js/index.js"></script>
  @RenderSection("scripts", false)
</body>
</html> 